### ISSUE TITLE
안되는데요..?

### ISSUE THREAD

**Issue by kiseok04111** [kimminsik-bernard/react-daum-postcode#1]
![image](https://user-images.githubusercontent.com/12725181/26917628-fbfdc6f0-4c69-11e7-95ba-86c480153b8d.png)
![image](https://user-images.githubusercontent.com/12725181/26917792-8eeda4da-4c6a-11e7-8348-1f3281f11597.png)

DaumPostcode.js 위치에서 에러납니다.

**Comment by kimminsik-bernard** [comment]
혹시 daum postcode 스크립트가 로드되었는지 확인해 보셨나요? [이 컴포넌트는 글로벌하게 `daum` 오브젝트가 선언되어있어야 합니다.](https://github.com/kimminsik-bernard/react-daum-postcode#사용)

**Comment by kiseok04111** [comment]
그러면 daum object를 어디에서 선언해주나요?
여기 내용에서는 따로 선언해준게 안보여서 모르겠습니다.

**Comment by kimminsik-bernard** [comment]
[README](https://github.com/kimminsik-bernard/react-daum-postcode#사용)에 적혀있는 것 처럼 `<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=false"></script>`와 같이 컴포넌트가 마운트되는 페이지에 직접 삽입해주셔야합니다.

[예제도 참고해주세요.](https://github.com/kimminsik-bernard/react-daum-postcode/tree/master/example)
