### ISSUE TITLE
onComplete 에러가 납니다. 

### ISSUE THREAD

**Issue by dajung-park** [kimminsik-bernard/react-daum-postcode#2]
해당 코드 적용하면 홈페이지 로딩이 계속 됩니다.
로딩을 취소하거나 브라우저 사이즈를 줄이면 화면이 나타나긴 하는데,,
그리고 this.handleAdrress 오타입니다..  if (data.addressType === 'R') {. 여기에도 . 문자가 들어가있어요.

**Comment by kimminsik-bernard** [comment]
브라우저 콘솔에 아무런 오류도 표시되지 않나요?
